### PR TITLE
Building for aarch64 on x64 macos

### PR DESCRIPTION
**Pull request by jadamcrain**

### CODE REVIEW

**Comment by cja769** [comment]
Is there a plan to try again to add support for ARM macos?

**Comment by jadamcrain** [comment]
This change actually went into 1.6.0. What language are you using?

**Comment by cja769** [comment]
Sorry I got confused by this saying it was closed and not merged. We're using Java. Looks like we're using 1.3.1 currently

**Comment by jadamcrain** [comment]
No worries. Please try 1.6.0 and let me know if you're able to run it on your M1/M2/M3.

**Comment by jadamcrain** [comment]
@cja769 Sorry for the confusion. It's 1.4.0 I'd like you to try. The other version was for DNP3.

**Pull request closed without merging**
